---
# Service for data from prometheus exporters per NATS Server
apiVersion: v1
kind: Service
metadata:
  name: nats-prometheus
spec:
  selector:
    prometheus: nats-prometheus
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: nats-prometheus
spec:
  scrapeInterval: "5s"
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: nats
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  endpoints:
  - port: metrics
