---
apiVersion: v1
kind: Pod
metadata:
  name: nats-box
  labels:
    app: nats-box
spec:
  containers:
  - name: nats-box
    image: synadia/nats-box:0.1.0
    imagePullPolicy: Always
    env:
    - name: NATS_URL
      value: nats
    - name: STAN_CLUSTER
      value: stan
    command:
     - "tail"
     - "-f"
     - "/dev/null"
