---
# Service used by Grafana as a datasource
apiVersion: v1
kind: Service
metadata:
  name: nats-surveyor-prometheus
  labels:
    app: nats-surveyor-prometheus
spec:
  selector:
    prometheus: nats-surveyor
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-surveyor-observations
data:
  test.json: |
    {
      "name": "latency.on.test",
      "topic": "latency.on.test",
      "credential": "/var/run/nats/creds/test/test.creds"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-surveyor
  labels:
    app: nats-surveyor
spec:
  selector:
    matchLabels:
      app: nats-surveyor
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-surveyor
    spec:
      volumes:
      - name: syscreds-volume
        secret:
          secretName: nats-sys-creds
      - name: nats-server-tls-volume
        secret:
          secretName: nats-server-tls
      - name: creds-volume
        secret:
          secretName: nats-test-creds
      - name: config-volume
        configMap:
          name: nats-surveyor-observations
      containers:
      - name: nats-surveyor
        image: synadia/nats-surveyor:0.0.1-alpha4
        ports:
        - containerPort: 7777
          name: metrics
        command: ["/bin/sh", "-c"]
        args:
        - set -x;
          cp /etc/nats/certs/ca.crt /usr/local/share/ca-certificates;
          ls -al /usr/local/share/ca-certificates;
          update-ca-certificates;
         /nats-surveyor -s=tls://nats:4222 -c=3 -creds=/var/run/nats/creds/sys/sys.creds -observe=/etc/nats/observations/;
        volumeMounts:
          - name: nats-server-tls-volume
            mountPath: /etc/nats/certs
          - name: syscreds-volume
            mountPath: /var/run/nats/creds/sys
          - name: creds-volume
            mountPath: /var/run/nats/creds/test
          - name: config-volume
            mountPath: /etc/nats/observations

        # Disable all cpu limits for the server.
        #
        resources:
          requests:
            cpu: 0
---
# Service used by Prometheus Operator to find the metrics endpoint.
apiVersion: v1
kind: Service
metadata:
  name: nats-surveyor
  labels:
    app: nats-surveyor
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: nats-surveyor
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: nats-surveyor
spec:
  scrapeInterval: "5s"
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: nats-surveyor
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-surveyor
  labels:
    app: nats-surveyor
spec:
  selector:
    matchLabels:
      app: nats-surveyor
  endpoints:
  - port: metrics
